import {useState,useEffect} from 'react';import type {CaseDefinition,LanguageProfile} from '@lexicon/shared-types';import type {NotebookTab} from '../state/gameStore';import type {InvestigationView} from '../investigation/selectInvestigationView';import type {InvestigationLearningProps} from '../investigation/RecordedStatements';import {InvestigationArtwork} from '../investigation/InvestigationArtwork';import {MeasuredPage} from '../investigation/pagination/MeasuredPage';import {ReadDocument} from '../investigation/pagination/ReadDocument';import {PageTurnSurface} from '../investigation/pagination/PageTurnSurface';import {InvestigationDecoration} from '../investigation/art/InvestigationDecoration';import {buildNotebookBlocks} from './buildNotebookBlocks';import type {NotebookReadingState} from './notebookReadingState';
export function NotebookReaderPage({definition,view,tab,reading,onReadingChange,learning,profile,onReviewEvidence,onOpenDeduction,onPaperCue}:{definition:CaseDefinition;view:InvestigationView;tab:NotebookTab;reading:NotebookReadingState;onReadingChange:(s:NotebookReadingState)=>void;learning:InvestigationLearningProps;profile?:LanguageProfile|undefined;onReviewEvidence:(id:string)=>void;onOpenDeduction:()=>void;onPaperCue?:(()=>void)|undefined}) {
 const [revealed,setRevealed]=useState<string|null>(null),[turn,setTurn]=useState(0);useEffect(()=>setRevealed(null),[tab,learning.translationMode]);
 const state=reading.tabs[tab],{strings}=learning;const data=buildNotebookBlocks(definition,view,tab,state.selectedId,strings,learning.translationMode,profile,revealed!==null&&revealed===state.selectedId);
 const patch=(next:Partial<typeof state>)=>onReadingChange({...reading,tabs:{...reading.tabs,[tab]:{...state,...next}}});
 const select=(id:string)=>{setRevealed(null);patch({selectedId:id,view:'detail',detailAnchor:null});};
 const fixed=Object.fromEntries(Object.entries(data.fixed).map(([id,f])=>[id,f.kind==='image'?<div className="notebook-profile-art" key={id}><InvestigationArtwork url={f.url} name={f.name} portrait={f.portrait}/><InvestigationDecoration kind="clip"/></div>:<button type="button" key={id} onClick={()=>{if(f.action==='review')onReviewEvidence(f.target);else if(f.action==='board')onOpenDeduction();else {const word=profile?.vocabulary[f.target];if(word?.contextsSeen[0]){learning.onRevealTranslation(f.target,word.contextsSeen[0]);patch({selectedId:f.target});setRevealed(f.target);}}}}>{f.label}</button>]));
 const heading=tab==='people'?strings.notebookPeopleHeading:tab==='evidence'?strings.notebookEvidenceHeading:tab==='vocabulary'?strings.notebookVocabularyHeading:strings.timeline;
 const itemBlocks=data.items.map(i=>({kind:'fixed' as const,id:i.id}));
 const card=(id:string,passive:boolean)=>{const i=data.items.find(i=>i.id===id)!;return <button type="button" className="notebook-index-card" tabIndex={passive?-1:undefined} aria-label={i.name} aria-pressed={i.id===data.selected?.id} onClick={passive?undefined:()=>select(i.id)}>{i.image&&<InvestigationArtwork url={i.image} name={i.name} portrait={i.portrait}/>}<span><strong>{i.name}</strong><small>{i.subtitle}</small></span></button>;};
 const empty=tab==='people'?strings.notebookEmptyPeople:tab==='evidence'?strings.evidenceEmpty:strings.notebookEmptyVocabulary;
 return <div className={`notebook-spread paginated-spread view-${state.view} tab-${tab}`}>
 {tab!=='timeline'&&<section className="notebook-index"><h3>{heading}</h3><MeasuredPage blocks={itemBlocks} anchor={state.contentsAnchor} onAnchorChange={a=>patch({contentsAnchor:a})} renderFragment={f=>card(f.blockId,false)} renderMeasurement={f=>card(f.blockId,true)} strings={strings} controlsLabel={strings.notebookContents} empty={<p>{empty}</p>} onPageTurn={()=>setTurn(n=>n+1)}/></section>}
 <article className={`notebook-detail ${tab==='people'?'notebook-person':tab==='evidence'?'notebook-evidence-detail':tab==='vocabulary'?'notebook-word-detail':'notebook-timeline-detail'}`} aria-label={data.selected?.name??heading}>
 {tab!=='timeline'&&<button type="button" className="notebook-back-contents" onClick={()=>patch({view:'contents'})}>{strings.notebookBackToContents}</button>}
 <PageTurnSurface pageKey={String(turn)} onPaperCue={onPaperCue}><ReadDocument blocks={data.blocks} fixed={fixed} label={data.selected?.name??heading} anchor={state.detailAnchor} onAnchorChange={a=>patch({detailAnchor:a})} learning={learning} revision={learning.translationMode+String(revealed)} onPageTurn={()=>setTurn(n=>n+1)} empty={<p>{empty}</p>}/></PageTurnSurface>
 </article>
 {[15,40,65,87].map(n=><InvestigationDecoration kind="ring" key={n} className={`ring-${n}`}/>)}
 </div>;
}
