import { z } from 'zod';
import type { UiStrings } from '@lexicon/shared-types';
import { ContentValidationError } from '../loader/ContentValidationError';

const uiStringsSchema = z
  .object({
    pagePrevious: z.string().min(1),
    pageNext: z.string().min(1),
    pagePosition: z.string().min(1),
    pagePreparing: z.string().min(1),
    notebookContents: z.string().min(1),
    notebookBackToContents: z.string().min(1),
    deductionCluesFace: z.string().min(1),
    deductionTimelineFace: z.string().min(1),
    deductionCompareFace: z.string().min(1),
    deductionConclusionFace: z.string().min(1),
    investigationBack: z.string().min(1),
    investigationCaseFile: z.string().min(1),
    investigationRelations: z.string().min(1),
    investigationReadFull: z.string().min(1),
    investigationResults: z.string().min(1),
    timelineConfirmSelection: z.string().min(1),

    deductionBoard: z.string().min(1),
    openDeductionBoard: z.string().min(1),
    openNotebookFromBoard: z.string().min(1),
    notebookPeopleHeading: z.string().min(1),
    notebookEvidenceHeading: z.string().min(1),
    notebookVocabularyHeading: z.string().min(1),
    notebookVocabularyExamples: z.string().min(1),
    notebookVocabularySources: z.string().min(1),
    notebookRelatedPeople: z.string().min(1),
    deductionFactsHeading: z.string().min(1),
    deductionCluesHeading: z.string().min(1),
    deductionInstructions: z.string().min(1),
    deductionClearSelection: z.string().min(1),
    deductionRelationships: z.string().min(1),
    vocabularyStageUnknown: z.string().min(1),
    vocabularyStageRecognized: z.string().min(1),
    vocabularyStageUnderstood: z.string().min(1),
    vocabularyStageUsed: z.string().min(1),
    vocabularyStageMastered: z.string().min(1),
    investigator: z.string().min(1),
    dialogue: z.string().min(1),
    dialogueError: z.string().min(1),
    objectiveHeading: z.string().min(1),
    caseFile: z.string().min(1),
    interact: z.string().min(1),
    move: z.string().min(1),
    pause: z.string().min(1),
    paused: z.string().min(1),
    resume: z.string().min(1),
    loadingGame: z.string().min(1),
    saveUnavailable: z.string().min(1),
    saveWriteFailed: z.string().min(1),
    saveRecoveryTitle: z.string().min(1),
    saveRecoveryBody: z.string().min(1),
    createFreshSave: z.string().min(1),
    cancel: z.string().min(1),
    notebook: z.string().min(1),
    evidence: z.string().min(1),
    people: z.string().min(1),
    vocabulary: z.string().min(1),
    timeline: z.string().min(1),
    timelineEmpty: z.string().min(1),
    timelineSelectEvent: z.string().min(1),
    timelineLocation: z.string().min(1),
    timelineSource: z.string().min(1),
    timelineConfidence: z.string().min(1),
    timelineSlotLabel: z.string().min(1),
    timelineSelectSlot: z.string().min(1),
    timelinePlace: z.string().min(1),
    timelinePlaced: z.string().min(1),
    timelineMismatch: z.string().min(1),
    timelineMismatchHint: z.string().min(1),
    contradictionUnavailable: z.string().min(1),
    contradictionSelectFacts: z.string().min(1),
    contradictionSelectedCount: z.string().min(1),
    contradictionSubmit: z.string().min(1),
    contradictionMismatch: z.string().min(1),
    contradictionMismatchHint: z.string().min(1),
    contradictionFound: z.string().min(1),
    conclusion: z.string().min(1),
    conclusionPrompt: z.string().min(1),
    conclusionSubmit: z.string().min(1),
    conclusionMismatch: z.string().min(1),
    conclusionUnavailable: z.string().min(1),
    caseClosed: z.string().min(1),
    caseReport: z.string().min(1),
    evidenceFound: z.string().min(1),
    keyContradiction: z.string().min(1),
    keyContradictionFound: z.string().min(1),
    keyContradictionMissing: z.string().min(1),
    peopleInterviewed: z.string().min(1),
    listeningTask: z.string().min(1),
    listeningTaskComplete: z.string().min(1),
    listeningTaskIncomplete: z.string().min(1),
    vocabularyEncountered: z.string().min(1),
    vocabularyMastered: z.string().min(1),
    listeningAccuracy: z.string().min(1),
    hintsUsed: z.string().min(1),
    overallProfile: z.string().min(1),
    noListeningData: z.string().min(1),
    close: z.string().min(1),
    notebookEmptyPeople: z.string().min(1),
    notebookStatementsHeading: z.string().min(1),
    notebookInterviewInProgress: z.string().min(1),
    notebookInterviewComplete: z.string().min(1),
    notebookEmptyVocabulary: z.string().min(1),
    evidenceEmpty: z.string().min(1),
    evidenceReview: z.string().min(1),
    openNotebook: z.string().min(1),
    minimapTitle: z.string().min(1),
    minimapPlayer: z.string().min(1),
    toggleMap: z.string().min(1),
    collapseObjective: z.string().min(1),
    expandObjective: z.string().min(1),
    collapseMap: z.string().min(1),
    expandMap: z.string().min(1),
    voiceReplay: z.string().min(1),
    voiceLoading: z.string().min(1),
    voiceBlocked: z.string().min(1),
    voiceError: z.string().min(1),
    vocabularyMode: z.string().min(1),
    vocabularyModeBeginner: z.string().min(1),
    vocabularyModeLearning: z.string().min(1),
    vocabularyModeImmersion: z.string().min(1),
    inspectVocabulary: z.string().min(1),
    revealTranslation: z.string().min(1),
    vocabularyMeaning: z.string().min(1),
    vocabularyContext: z.string().min(1),
    vocabularyStageSeen: z.string().min(1),
    vocabularyTutorial: z.string().min(1),
    vocabularyLearningError: z.string().min(1),
    vocabularyResetTitle: z.string().min(1),
    vocabularyResetBody: z.string().min(1),
    listeningTimestamp: z.string().min(1),
    listeningPlay: z.string().min(1),
    listeningPause: z.string().min(1),
    listeningReplay: z.string().min(1),
    listeningQuestion: z.string().min(1),
    listeningTranscript: z.string().min(1),
    listeningTranslation: z.string().min(1),
    listeningShowTranscript: z.string().min(1),
    listeningHint: z.string().min(1),
    listeningRetry: z.string().min(1),
    settingsVolume: z.string().min(1),
    settingsSubtitles: z.string().min(1),
    settingsSubtitlesAuto: z.string().min(1),
    settingsSubtitlesOn: z.string().min(1),
    settingsSubtitlesOff: z.string().min(1),
    settingsReducedMotion: z.string().min(1),
    settingsRecovered: z.string().min(1),
    settingsUnavailable: z.string().min(1),
    listeningLoading: z.string().min(1),
    listeningPlaying: z.string().min(1),
    listeningPaused: z.string().min(1),
    listeningEnded: z.string().min(1),
    listeningPlaybackError: z.string().min(1),
    listeningMismatch: z.string().min(1),
    listeningCompleted: z.string().min(1),
  })
  .strict();

function formatIssue(issue: z.ZodIssue): string {
  const path = issue.path.length > 0 ? issue.path.join('.') : '(root)';
  return `${path}: ${issue.message}`;
}

export function parseUiStrings(raw: unknown, source: string): UiStrings {
  const result = uiStringsSchema.safeParse(raw);
  if (!result.success) {
    const issues = result.error.issues.map(formatIssue);
    throw new ContentValidationError(source, issues);
  }
  return result.data;
}
